name: Setup Gradle
inputs:
  arguments:
    description: Gradle command arguments
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: gradle
    - name: Ensure gradlew executable
      run: chmod +x ./gradlew
      shell: bash
    - name: Run Gradle
      run: ./gradlew ${{ inputs.arguments }}
      shell: bash
